import { Metadata } from 'next';
import YouTubeTagsGenerator from '../_components/youtube-tags';

export const metadata: Metadata = {
  title: 'YouTube Tags Generator | AI-Powered Video Tags',
  description: 'Generate relevant YouTube video tags with our AI-powered tool to enhance your contents visibility and searchability.',
  keywords: 'YouTube tags generator, video tags, content optimization, AI generator',
};

interface FAQ {
  question: string;
  answer: string;
}

const faqs: FAQ[] = [
  {
    question: 'How do YouTube tags affect my videos performance?',
    answer: 'Tags help YouTube understand the content and context of your video, improving its chances of appearing in relevant search results and recommendations.',
  },
  {
    question: 'Can I customize the tags generated by the AI?',
    answer: 'Yes, our tool allows you to edit and customize the generated tags to better fit your specific content and target audience.',
  },
  // Add more FAQs as needed
];

const YouTubeTagsGeneratorPage: React.FC = () => {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-3xl font-bold mb-6">YouTube Tags Generator</h1>
      <YouTubeTagsGenerator />
      
      {/* SEO-Optimized Content */}
      <section className="my-8">
        <h2 className="text-2xl font-semibold mb-4">Benefits of Optimizing Your YouTube Tags</h2>
        <ul className="list-disc list-inside text-gray-700">
          <li>Enhances video searchability</li>
          <li>Connects your content with relevant audiences</li>
          <li>Improves video ranking in search results</li>
          <li>Increases the likelihood of appearing in suggested videos</li>
        </ul>
      </section>
    </div>
  );
};

export default YouTubeTagsGeneratorPage;